options:
  formatter: stylish
  merge-default-rules: true
  max-warnings: 0
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**'
    - 'coverage/**'
    - 'dist/**'
    - 'test/**'
    - 'app/styles/react-slick-overrides.scss'
    - 'app/components/landing/parts/SmartContractWindow.module.scss'
    - 'app/components/landing/parts/Interoperable.module.scss'
    - 'app/components/landing/parts/SpinningEthereum.module.scss'
    - 'app/components/shared/SuccessTick.module.scss'
    - 'app/styles/vendor/**'
    - 'app/components/shared/forms/form-field/FormFieldDatePicker.module.scss'
rules:
  no-transition-all: 0
  nesting-depth:
        - 4
        - max-depth: 4
  property-sort-order: 0
  quotes:
    - 1
    - style: double
